services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: day4-rabbitmq
    ports:
      - "5672:5672" # AMQP — producer/consumer kết nối vào đây
      - "15672:15672" # Web UI: http://localhost:15672 (guest / guest)
